name: Deploy & Run Supabase Edge Function

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/1 * * * *"   # runs every 1 minute

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Bun (for Supabase CLI)
        uses: oven-sh/setup-bun@v1

      - name: Install Supabase CLI
        run: bun install -g supabase

      - name: Deploy function
        run: |
          supabase functions deploy fetch-mpesa-emails --project-ref ${{ secrets.PROJECT_REF }} --no-verify-jwt
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_URL: https://wzdodbpfdvmsbtwecdvk.supabase.co
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          GMAIL_CLIENT_ID: 876393797729-66bhkv1k33kg7vvvr2bdig0q55lbfi1r.apps.googleusercontent.com
          GMAIL_CLIENT_SECRET: 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
          GMAIL_REFRESH_TOKEN: 1//04M4xvQpyTRRwCgYIARAAGAQSNwF-L9IrmUCAnLAYRkZvf4GyTL6sem3Z4HzqPP7eLbK43k6ynR3VRy_HcL-9ndxjue1OsnO5_5U
